version: '4.0'

actions:
  measures_primary:
    run: ehrql:v1 generate-measures analysis/measure_def.py 
      --output output/measures/measures_overall.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall.csv
